version: '3'
services:
  android-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../projects:/home/developer/projects  # 项目目录
      - ~/.gradle:/home/developer/.gradle    # 共享Gradle缓存
      - ~/.m2:/home/developer/.m2            # 共享Maven缓存
    ports:
      - "5037:5037"  # ADB端口
    environment:
      - DISPLAY=${DISPLAY:-:0.0}
    tty: true
    stdin_open: true
    command: sleep infinity  # 保持容器运行
    restart: unless-stopped
    container_name: android-development
